# Generated by Django 3.0.8 on 2020-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
