# Generated by Django 3.0.8 on 2020-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPP_Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('prob_name', models.CharField(max_length=1000)),
                ('prob_link', models.CharField(max_length=1000)),
                ('sol_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CPP_tutorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=1000)),
                ('tut_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CpProblem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('prob_name', models.CharField(max_length=1000)),
                ('prob_link', models.CharField(max_length=1000)),
                ('sol_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cptutorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=1000)),
                ('tut_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='pythonProblem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('prob_name', models.CharField(max_length=1000)),
                ('prob_link', models.CharField(max_length=1000)),
                ('sol_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='pythontutorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=1000)),
                ('tut_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
